### ISSUE TITLE
Should allow for multiple model entries

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RITE#134]
The following error was encountered when working with the Adept project.
```
Loading manifest for 'ADEPT Engine'...
Clear graph http://rack001/model
Clear graph http://rack001/mbsemodel
Clear graph http://rack001/adeptdata
Load OWL 01_model/AGENTS.owl to http://rack001/model
Load OWL 01_model/ANALYSIS.owl to http://rack001/model
Load OWL 01_model/BASELINE.owl to http://rack001/model
Load OWL 01_model/CLAIM.owl to http://rack001/model
Load OWL 01_model/CONFIDENCE.owl to http://rack001/model
Load OWL 01_model/DOCUMENT.owl to http://rack001/model
Load OWL 01_model/EntityResolution.owl to http://rack001/model
Load OWL 01_model/FILE.owl to http://rack001/model
Load OWL 01_model/HARDWARE.owl to http://rack001/model
Load OWL 01_model/HAZARD.owl to http://rack001/model
Load OWL 01_model/MODEL.owl to http://rack001/model
Load OWL 01_model/PROCESS.owl to http://rack001/model
Load OWL 01_model/PROV-S.owl to http://rack001/model
Load OWL 01_model/REQUIREMENTS.owl to http://rack001/model
Load OWL 01_model/REVIEW.owl to http://rack001/model
Load OWL 01_model/SECURITY.owl to http://rack001/model
Load OWL 01_model/SOFTWARE.owl to http://rack001/model
Load OWL 01_model/SYSTEM.owl to http://rack001/model
Load OWL 01_model/TESTING.owl to http://rack001/model
Load OWL 01_model/RESOLUTIONS.owl to http://rack001/model
Load OWL 02_model/mbse.owl to http://rack001/mbsemodel
Store nodegroups
Stored: ADEPT requirements on designed parts mapped to manufactured parts
Stored: ADEPT as-manufactured blade thickness
Stored: ADEPT blade thickness by manufacturer
Stored: ADEPT hrs to inspection
Stored: ADEPT manuf blade thick vs prob distress
Stored: ADEPT probOfDistress plot one turbine
Stored: ADEPT probOfDistress polar
Stored: ADEPT teamcenter requirements
Error: Not currently supporting multiple entries for this node: ["http://rack001/model","http://rack001/mbsemodel"]
```
The instance data import.yaml file that caused this error had the following line:
```
data-graph: http://rack001/adeptdata
model-graphs:
- http://rack001/model
- http://rack001/mbsemodel
ingestion-steps:
- class: http://arcos.rack/PROV-S#ACTIVITY
  csv: ingest_ACTIVITY.csv

- class: http://arcos.rack/mbse#AircraftDesign
  csv: ingest_AircraftDesign.csv
- class: http://arcos.rack/mbse#EngineDesign
  csv: ingest_EngineDesign.csv
...
```
I believe RITE should allow this. Project files to replicate this can be found [here](https://github.build.ge.com/MBSE/MBE_E2E_Demo/releases/tag/0.1.0) in our internal Adept project.
